package com.example.data.game

import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import androidx.core.content.FileProvider
import java.io.File

/**
 * Handles checking, configuring settings.ini, and launching the GTA SA-MP Game Client.
 */
object GameClientLauncher {

  // Common package names for SA-MP mobile clients
  val KNOWN_CLIENT_PACKAGES = listOf(
    "com.rockstargames.gtasa",
    "com.samp.mobile",
    "com.liverussia.cr",
    "com.arizona.game",
    "com.blackrussia.online",
    "ru.unisamp_mobile.game",
    "com.br.top"
  )

  /**
   * Check if any compatible GTA SA / SA-MP Client APK is installed on the phone.
   */
  fun findInstalledClientPackage(context: Context): String? {
    val pm = context.packageManager
    for (pkg in KNOWN_CLIENT_PACKAGES) {
      try {
        pm.getPackageInfo(pkg, 0)
        return pkg
      } catch (e: PackageManager.NameNotFoundException) {
        // Try next
      }
    }
    return null
  }

  /**
   * Write SA-MP settings.ini so that the game client connects directly to the specified server.
   */
  fun writeSampSettings(
    context: Context,
    playerName: String,
    serverIp: String,
    serverPort: Int,
    targetPackage: String?
  ): Boolean {
    return try {
      val candidateDirs = mutableListOf<File>()

      // 1. In our own app's files directory
      val appExtFiles = context.getExternalFilesDir(null)
      if (appExtFiles != null) {
        candidateDirs.add(File(appExtFiles, "SAMP"))
        candidateDirs.add(appExtFiles)
      }

      // 2. In /storage/emulated/0/Android/data/<package>/files/SAMP
      val targetPkg = targetPackage ?: "com.rockstargames.gtasa"
      val commonAndroidData = File("/storage/emulated/0/Android/data/$targetPkg/files/SAMP")
      candidateDirs.add(commonAndroidData)

      val content = StringBuilder()
        .appendLine("# SA-MP Mobile Configuration Generated by SA-MP Launcher")
        .appendLine("[client]")
        .appendLine("name=$playerName")
        .appendLine("server=$serverIp")
        .appendLine("port=$serverPort")
        .appendLine("fps=60")
        .appendLine("timestamp=1")
        .appendLine("fastconnect=1")
        .toString()

      for (dir in candidateDirs) {
        try {
          if (!dir.exists()) {
            dir.mkdirs()
          }
          val iniFile = File(dir, "settings.ini")
          iniFile.writeText(content)
        } catch (e: Exception) {
          // Continue to next possible location
        }
      }
      true
    } catch (e: Exception) {
      false
    }
  }

  /**
   * Launch the game client with Server & Nickname Intent extras.
   */
  fun launchGame(
    context: Context,
    packageName: String,
    serverIp: String,
    serverPort: Int,
    playerName: String
  ): Result<Unit> {
    return try {
      // 1. First write settings.ini
      writeSampSettings(context, playerName, serverIp, serverPort, packageName)

      // 2. Launch Intent
      val intent = context.packageManager.getLaunchIntentForPackage(packageName)
        ?: return Result.failure(Exception("Cannot find launch intent for $packageName"))

      intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
      intent.putExtra("server", serverIp)
      intent.putExtra("port", serverPort)
      intent.putExtra("name", playerName)
      intent.putExtra("ip", serverIp)
      intent.putExtra("nick", playerName)

      context.startActivity(intent)
      Result.success(Unit)
    } catch (e: Exception) {
      Result.failure(e)
    }
  }

  /**
   * Install an APK file downloaded locally using Android PackageInstaller.
   */
  fun installApk(context: Context, apkFile: File): Result<Unit> {
    return try {
      if (!apkFile.exists() || apkFile.length() == 0L) {
        return Result.failure(Exception("APK file does not exist or is empty"))
      }

      val intent = Intent(Intent.ACTION_VIEW).apply {
        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        val uri = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
          FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", apkFile)
        } else {
          Uri.fromFile(apkFile)
        }
        setDataAndType(uri, "application/vnd.android.package-archive")
      }
      context.startActivity(intent)
      Result.success(Unit)
    } catch (e: Exception) {
      Result.failure(e)
    }
  }
}
